# Generated by Django 4.1.7 on 2023-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "Korean Won"), ("usd", "Dollar")], max_length=5
            ),
        ),
    ]
