# Generated by Django 4.1.7 on 2023-05-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_alter_room_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
