# Generated by Django 4.1.7 on 2023-03-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="perk",
            name="details",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="perk",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
